package com.example.smartexpensecalendar.sms.config

object DirectionPhrases {

    /**
     * Confirmed INCOMING (Income, Refunds, CC Bill Payments)
     * RULE: Credit phrases should be checked before debit phrases.
     */
    val creditPhrases = setOf(
        "PAYMENT RECEIVED",
        "RECEIVED TOWARDS",
        "PAYMENT OF {CUR} IS RECEIVED",
        "PAYMENT OF {CUR} IS RECIEVED",
        "IS RECEIVED",
        "IS RECIEVED",
        "CREDITED TO",
        "CREDITED INTO",
        "CREDITED IN",
        "AMOUNT CREDITED",
        "AMT CREDITED",
        "SALARY CREDITED",
        "SALARY DEPOSITED",
        "REFUND CREDITED",
        "CASHBACK CREDITED",
        "INTEREST CREDITED",
        "REWARD CREDITED",
        "FUNDS RECEIVED",
        "AMOUNT RECEIVED",
        "RECEIVED FROM",
        "RECEIVED ON",
        "RECEIVED {CUR}",
        "RECIEVED {CUR}",
        "DEPOSITED INTO",
        "DEPOSITED TO",
        "DEPOSITED IN",
        "DEPOSITED TOWARDS",
        "MONEY RECEIVED",
        "INWARD REMITTANCE",
        "RECEIVED VIA UPI",
        "CREDIT TRANSACTION",
        "CREDITED SUCCESSFULLY",
        "GOT FRESH FUNDS",
        "TOWARDS YOUR CREDIT CARD",
        "TOWARDS YOU YES BANK",
        "MONEY CREDITED",
        "CREDITED FOR {CUR}",
        "SUCCESSFULLY CREDITED",
        "CREDITED WITH",
        "REVERSAL OF",
        "LOADED IN WALLET",
        "ADDED IN WALLET",
        "ಜಮಾ ಕಿಯಾ ಗया",
        "जमा किया गया",
        "ईएमआई प्राप्त हुई"
    )

    /**
     * Confirmed OUTGOING (Expenses, ATM, Outward Transfers)
     */
    val debitPhrases = setOf(
        "DEBITED FROM",
        "DEBITED TOWARDS",
        "AMOUNT DEBITED",
        "AMOUNT DEDUCTED",
        "DEDUCTED FROM",
        "AMT DEDUCTED",
        "SPENT ON",
        "SPENT AT",
        "SPENT RS",
        "SPENT INR",
        "SPENT FROM",
        "SPENT USING",
        "PURCHASE AT",
        "PURCHASE OF",
        "PURCHASE FOR",
        "PURCHASE MADE",
        "PURCHASE USING",
        "PURCHASE ON",
        "PAID TO",
        "PAID VIA",
        "PAID USING",
        "PAID RS",
        "PAID INR",
        "PAYMENT OF RS",
        "PAYMENT OF INR",
        "CASH WITHDRAWAL",
        "ATM WITHDRAWAL",
        "WITHDRAWN FROM",
        "WITHDRAWN AT",
        "WITHDRAWN {CUR}",
        "SENT TO",
        "SENT FROM",
        "SENT FROM YOUR",
        "MONEY SENT",
        "MONEY DEBITED",
        "DEBITED FOR {CUR}",
        "DEBITED WITH",
        "CHARGED TO",
        "CHARGE OF {CUR}",
        "AUTOPAY SUCCESSFUL",
        "E-MANDATE SUCCESS",
        "BILL PAYMENT",
        "MERCHANT PAYMENT",
        "DEBIT TRANSACTION",
        "TXN OF {CUR}",
        "UPI PAYMENT",
        "UPI TXN",
        "WAS DEBITED",
        "SENT FROM YOUR ACCOUNT",
        "TRANSFERRED FROM YOUR",
        "ನಿಕಾಲೇ ಗಯೇ",
        "निकाले गए"
    )
}
