package com.example.smartexpensecalendar.sms.config

object MessageTypeKeywords {

    val transactionKeywords = setOf(
        "DEBITED",
        "CREDITED",
        "PAID",
        "RECEIVED",
        "WITHDRAWN",
        "PURCHASE",
        "PURCHASED",
        "CASHBACK CREDITED",
        "REFUND PROCESSED",
        "SPENT",
        "POS",
        "ATM",
        "ATM WDL",
        "ATM WITHDRAWAL",
        "CASH WITHDRAWAL",
        "UPI PAYMENT",
        "PAID VIA",
        "PAID USING",
        "MERCHANT",
        "CARD USED",
        "CARD PURCHASE",
        "DEBIT TRANSACTION",
        "ON CARD",
        "SWIPED",
        "PAYMENT OF RS",
        "PAYMENT SUCCESSFUL",
        "TRANSACTION SUCCESSFUL",
        "TRANSFER SUCCESSFUL",
        "REFUND SUCCESSFUL",
        "RECHARGE SUCCESSFUL",
        "ADDED TO",
        "TRANSFERRED",
        "REFUND",
        "RECHARGE",
        "AUTOPAY",
        "E-MANDATE",
        "TXN AMT",
        "PAYMENT UPDATED",
        "DEDUCTED"
    )

    val informationKeywords = setOf(
        "STATEMENT GENERATED",
        "BALANCE UPDATED",
        "UPI REGISTRATION",
        "UPI LINK REQUEST",
        "CARD UPDATED",
        "INTEREST UPDATED",
        "TDS",
        "E-STATEMENT",
        "ACCOUNT SUMMARY",
        "CURRENT BALANCE",
        "AVAILABLE BALANCE",
        "CREDIT LIMIT",
        "ACCOUNT UPDATED",
        "REGISTRATION",
        "REGISTERED",
        "KYC",
        "KYC UPDATED",
        "PROFILE UPDATED",
        "MOBILE UPDATED",
        "EMAIL UPDATED",
        "CARD ACTIVATED",
        "CARD BLOCKED",
        "CARD UNBLOCKED",
        "SERVICE REQUEST",
        "STATEMENT",
        "DUPLICATE STATEMENT",
        "CARDMEMBER",
        "PASSWORD FORMAT",
        "UPDATED TERMS",
        "ACTIVATION",
        "ACTIVATED",
        "PIN SET",
        "PASSWORD RESET",
        "DEVICE REGISTERED",
        "LOW BALANCE",
        "A/C BAL",
        "BAL IS NOW BELOW",
    )

    val obligationKeywords = setOf(
        "DUE",
        "MINIMUM AMOUNT DUE",
        "EMI DUE",
        "REPAYMENT",
        "PAY BEFORE",
        "PAYMENT DUE",
        "OUTSTANDING",
        "BOUNCE CHARGE",
        "COLLECT REQUEST",
        "MANDATE CREATED",
        "AUTOPAY REGISTRATION",
        "BILL GENERATED",
        "TOTAL DUE",
        "MINIMUM DUE",
        "PAYMENT REQUIRED",
        "AUTOPAY DUE",
        "OVERDUE",
        "PAST DUE",
        "DUE DATE",
        "MANDATE"
    )

    val promotionalKeywords = setOf(
        "PRE-APPROVED",
        "LOAN OFFER",
        "CASHBACK OFFER",
        "ELIGIBLE FOR",
        "LIFETIME FREE",
        "PERSONAL LOAN",
        "APPLY NOW",
        "ELIGIBLE",
        "UPGRADE YOUR CARD",
        "INSTANT LOAN",
        "OFFER",
        "EXCLUSIVE OFFER"
    )
}
