package com.example.smartexpensecalendar.sms.config

object MessageTypeKeywords {

    val transactionKeywords = setOf(
        "DEBITED",
        "CREDITED",
        "PAID",
        "RECEIVED",
        "WITHDRAWN",
        "PURCHASE",
        "PURCHASED",
        "CASHBACK",
        "REFUND",
        "SPENT",
        "POS",
        "ATM",
        "TXN",
        "PAYMENT",
        "TRANSFER",
        "RECHARGE",
        "AUTOPAY",
        "DEDUCTED",
        "SENT",
        "ADDED",
        "SUCCESSFUL",
        "WDL",
        "SWIPED",
        "CHARGED"
    )

    val informationKeywords = setOf(
        "STATEMENT GENERATED",
        "BALANCE UPDATED",
        "UPI REGISTRATION",
        "UPI LINK REQUEST",
        "CARD UPDATED",
        "INTEREST UPDATED",
        "TDS",
        "E-STATEMENT",
        "ACCOUNT SUMMARY",
        "CURRENT BALANCE",
        "AVAILABLE BALANCE",
        "CREDIT LIMIT",
        "ACCOUNT UPDATED",
        "REGISTRATION",
        "REGISTERED",
        "KYC",
        "KYC UPDATED",
        "PROFILE UPDATED",
        "MOBILE UPDATED",
        "EMAIL UPDATED",
        "CARD ACTIVATED",
        "CARD BLOCKED",
        "CARD UNBLOCKED",
        "SERVICE REQUEST",
        "STATEMENT",
        "DUPLICATE STATEMENT",
        "CARDMEMBER",
        "PASSWORD FORMAT",
        "UPDATED TERMS",
        "ACTIVATION",
        "ACTIVATED",
        "PIN SET",
        "PASSWORD RESET",
        "DEVICE REGISTERED",
        "LOW BALANCE",
        "A/C BAL",
        "BAL IS NOW BELOW",
        "OTP IS",
        "FOR TXN OF",
        "TELL US ABOUT YOUR",
        "EXPERIENCE",
        "HOW DID YOU LIKE"
    )

    val obligationKeywords = setOf(
        "DUE",
        "MINIMUM AMOUNT DUE",
        "EMI DUE",
        "REPAYMENT",
        "PAY BEFORE",
        "PAYMENT DUE",
        "OUTSTANDING",
        "BOUNCE CHARGE",
        "COLLECT REQUEST",
        "MANDATE CREATED",
        "AUTOPAY REGISTRATION",
        "BILL GENERATED",
        "TOTAL DUE",
        "MINIMUM DUE",
        "PAYMENT REQUIRED",
        "AUTOPAY DUE",
        "OVERDUE",
        "PAST DUE",
        "DUE DATE",
        "MANDATE",
        "STATEMENT:",
        "WILL BE DEBITED",
        "देय तिथि",
        "धनराशि बनाए रखें"
    )

    val promotionalKeywords = setOf(
        "PRE-APPROVED",
        "LOAN OFFER",
        "CASHBACK OFFER",
        "ELIGIBLE FOR",
        "LIFETIME FREE",
        "PERSONAL LOAN",
        "APPLY NOW",
        "ELIGIBLE",
        "UPGRADE YOUR CARD",
        "INSTANT LOAN",
        "OFFER",
        "EXCLUSIVE OFFER"
    )
}
