package com.example.smartexpensecalendar.sms.config

object MessageTypePhrases {

    val transactionPhrases = setOf(

        // Credit
        "CREDITED TO",
        "CREDITED INTO",
        "AMOUNT CREDITED",
        "SALARY CREDITED",
        "REFUND CREDITED",
        "CASHBACK CREDITED",
        "INTEREST CREDITED",
        "PAYMENT RECEIVED",
        "FUNDS RECEIVED",
        "AMOUNT RECEIVED",
        "RECEIVED FROM",
        "DEPOSITED INTO",
        "DEPOSITED TO",
        "MONEY RECEIVED",

        // Debit
        "DEBITED FROM",
        "DEBITED TOWARDS",
        "AMOUNT DEBITED",
        "AMOUNT DEDUCTED",
        "DEDUCTED FROM",
        "SPENT ON",
        "SPENT AT",
        "PURCHASE MADE",
        "PURCHASE USING",
        "PURCHASE ON",
        "PAID TO",
        "PAID VIA",
        "PAID USING",
        "PAYMENT OF RS",
        "PAYMENT OF INR",
        "CASH WITHDRAWAL",
        "ATM WITHDRAWAL",
        "WITHDRAWN FROM",
        "WITHDRAWN AT",
        "SENT TO",
        "MONEY SENT",
        "CHARGED TO",
        "AUTOPAY SUCCESSFUL",
        "E-MANDATE SUCCESS",
        "BILL PAYMENT",
        "MERCHANT PAYMENT",
        "DEBIT TRANSACTION",
        "TXN OF RS",
        "TXN OF INR",
        "UPI PAYMENT",
        "UPI TXN",

        // Transfer
        "FUND TRANSFER",
        "MONEY TRANSFER",
        "ACCOUNT TO ACCOUNT",
        "BENEFICIARY",
        "TRANSFERRED TO",
        "TRANSFERRED FROM",
        "IMPS TRANSFER",
        "NEFT TRANSFER",
        "RTGS TRANSFER",
        "UPI TRANSFER",

        // Refund
        "REFUND INITIATED",
        "REFUND PROCESSED",
        "REFUND CREDITED",
        "REFUND SUCCESSFUL",
        "REVERSAL PROCESSED"
    )

    val informationPhrases = setOf(
        "STATEMENT GENERATED",
        "DUPLICATE STATEMENT",
        "E-STATEMENT",
        "PASSWORD FORMAT",
        "KYC UPDATED",
        "PROFILE UPDATED",
        "MOBILE UPDATED",
        "EMAIL UPDATED",
        "DEVICE REGISTERED",
        "REGISTRATION INITIATED",
        "UPI REGISTRATION",
        "CARD ACTIVATED",
        "CARD BLOCKED",
        "CARD UNBLOCKED",
        "CREDIT LIMIT",
        "ACCOUNT SUMMARY",
        "AVAILABLE BALANCE",
        "CURRENT BALANCE",
        "SERVICE REQUEST",
        "BALANCE UPDATED",
        "ACCOUNT UPDATED",
        "STATEMENT AVAILABLE",
        "KYC STATUS",
        "LIMIT UPDATED",
        "REQUEST PROCESSED",
        "SUCCESSFULLY REGISTERED",

        // Important leakage cases
        "USAGE SETTINGS",
        "CARD USAGE",
        "RESET YOUR PIN",
        "ACCOUNT OPENING",
        "VIEW/MANAGE CARD USAGE",
        "ENABLE INTERNATIONAL",
        "ENABLING INTERNATIONAL",
        "ACCOUNT IS NOW ACTIVE",
        "ACTIVATE YOUR DEBIT CARD",
        "REQUEST HAS BEEN PROCESSED",
        "UPI LINK REQUEST",
        "LINK YOUR UPI",
        "CARD USAGE SETTINGS",
        "TRANSACTION LIMITS",
        "INTERNATIONAL ONLINE USAGE",
        "INCORRECT PIN USAGE",
        "FORGOT YOUR PIN",
        "REQUEST FOR ENABLING",
        "APPLICATION HAS BEEN RECEIVED",
        "ACCOUNT APPLICATION",
        "TECHNICAL ISSUE REPORT",
        "VEHICLE INSURANCE",
        "MISSED CALL",
        "READY TO USE",
        "CARD IS READY TO USE"
    )

    val obligationPhrases = setOf(
        "PAYMENT DUE",
        "TOTAL DUE",
        "MINIMUM DUE",
        "AMOUNT DUE",
        "PAY BEFORE",
        "PAY BY",
        "OVERDUE",
        "PAST DUE",
        "DUE DATE",
        "EMI DUE",
        "REPAYMENT DUE",
        "PAYMENT REQUIRED",
        "OUTSTANDING AMOUNT",
        "BILL GENERATED",
        "AUTOPAY DUE",
        "MANDATE CREATED",
        "COLLECT REQUEST"
    )

    val promotionalPhrases = setOf(
        "PRE-APPROVED LOAN",
        "LOAN OFFER",
        "INSTANT LOAN",
        "PERSONAL LOAN OFFER",
        "ELIGIBLE FOR LOAN",
        "EXCLUSIVE OFFER",
        "CASHBACK OFFER",
        "LIFETIME FREE CARD",
        "UPGRADE YOUR CARD",
        "APPLY NOW"
    )

    val strongInformationPhrases = setOf(
        "WILL BE DEBITED",
        "USAGE SETTINGS",
        "VIEW/MANAGE CARD USAGE",
        "INTERNATIONAL ONLINE USAGE",
        "REQUEST FOR ENABLING",
        "REQUEST HAS BEEN PROCESSED",
        "APPLICATION HAS BEEN RECEIVED",
        "ACCOUNT APPLICATION",
        "ACCOUNT IS NOW ACTIVE",
        "ACCOUNT ACTIVATED",
        "CARD ACTIVATED",
        "CARD IS READY TO USE",
        "READY TO USE",
        "INCORRECT PIN USAGE",
        "FORGOT YOUR PIN",
        "PIN ATTEMPTS",
        "TRANSACTION RESTRICTION",
        "TRANSACTION LIMIT",
        "CONSENT FOR AVAILING",
        "PAYMENT WAS NOT COMPLETED",
        "NEUCOINS",
        "REWARD BENEFITS",
        "CARD ACTIVATED",
        "CARD HAS BEEN ACTIVATED",
        "ACCOUNT IS NOW ACTIVE",
        "ACCOUNT ACTIVATED",
        "APPLICATION HAS BEEN RECEIVED",
        "APPLICATION RECEIVED",
        "TRANSACTION RESTRICTION",
        "TRANSACTION RESTRICTION SETTING",
        "TRANSACTION LIMIT",
        "TRANSACTION LIMITS",
        "READY TO USE",
        "CONSENT FOR AVAILING",
        "USAGE SETTINGS",
        "VIEW/MANAGE CARD USAGE",
        "ENABLE INTERNATIONAL",
        "ENABLING INTERNATIONAL",
        "INTERNATIONAL ONLINE USAGE",
        "INCORRECT PIN USAGE",
        "PIN ATTEMPTS",
        "FORGOT YOUR PIN",
        "WILL BE DEBITED",
        "IF DEBITED",
        "WAS NOT COMPLETED",
        "NOT COMPLETED",
        "AUTOMATIC REFUND PROCESSED",
        "CONSENT FOR AVAILING",
        "IS NOW ACTIVE",
        "APPLICATION HAS BEEN RECEIVED",
        "CREDIT CARD HAS BEEN ACTIVATED",
        "HAS BEEN ACTIVATED",
        "TRANSACTION RESTRICTION",
        "TRANSACTION LIMIT",
        "READY TO USE",
        "NEUCOINS",
        "REFERRAL BENEFITS",
        "IS NOW ACTIVE",
        "APPLICATION HAS BEEN RECEIVED",

        "WE HAVE APPLIED USAGE SETTINGS",
        "VIEW/MANAGE CARD USAGE",

        "ENABLING INTERNATIONAL ONLINE USAGE",

        "INCORRECT PIN USAGE",
        "PIN ATTEMPTS",

        "PAYMENT WAS NOT COMPLETED",

        "TRANSACTION RESTRICTION",
        "TRANSACTION RESTRICTIONS",

        "TRANSACTION LIMIT",
        "TRANSACTION LIMITS",

        "READY TO USE",

        "CONSENT FOR AVAILING",

        "NEUCOINS",
        "REFERRAL BENEFITS"
    )
}
