package com.example.smartexpensecalendar.sms.config

object MessageTypePhrases {

    // --- CURRENCY AGNOSTIC PATTERNS ---
    const val CUR_PLACEHOLDER = "{CUR}"

    // --- STAGE 1: OBLIGATION (Reminders / Future Actions) ---
    val obligationPhrases = setOf(
        "IS DUE ON",
        "OVERDUE ON",
        "MINIMUM AMOUNT DUE",
        "PAYMENT DUE DATE",
        "PAY BEFORE",
        "TOTAL AMOUNT DUE",
        "REPAYMENT OF",
        "MANDATE CREATED",
        "AUTOPAY REGISTRATION",
        "WILL BE DEBITED ON",
        "WILL BE AUTO DEBITED",
        "PENDING ON",
        "DUE BY",
        "TOTAL DUE",
        "MIN. DUE",
        "MINIMUM DUE",
        "AMOUNT DUE",
        "IS DUE FOR PAYMENT",
        "MAINTAIN ADEQUATE BALANCE",
        "ENSURE SUFFICIENT BALANCE",
        "SCHEDULED ON",
        "REQUESTED A PAYMENT",
        "DUE DATE",
        "ईएमआई की देय तिथि",
        "धनराशि बनाए रखें"
    )

    // --- STAGE 2: TRANSACTION (Confirmed Money Movement) ---
    
    val transactionDebitPhrases = setOf(
        "SPENT {CUR}",
        "{CUR} SPENT",
        "TXN {CUR}",
        "{CUR} DEBITED",
        "TXN OF {CUR}",
        "TRANSACTION OF {CUR}",
        "CHARGE OF {CUR}",
        "SPENT ON",
        "SPENT OF",
        "SPENT USING",
        "SPENT FROM",
        "SPENT AT",
        "PAID TO",
        "PAID VIA",
        "PAID USING",
        "PAYMENT MADE",
        "PAID {CUR}",
        "DEBITED FROM",
        "WAS DEBITED",
        "IS DEBITED",
        "HAS BEEN DEBITED",
        "MONEY DEBITED",
        "DEBITED FOR {CUR}",
        "SENT FROM YOUR ACCOUNT",
        "DEDUCTED FROM",
        "AMT DEDUCTED",
        "WITHDRAWN VIA",
        "WITHDRAWN FROM",
        "WITHDRAWN {CUR}",
        "CASH WITHDRAWAL",
        "PURCHASE MADE",
        "PURCHASED AT",
        "SWIPED ON",
        "CHARGED ON",
        "AUTOPAY SUCCESSFUL",
        "E-MANDATE SUCCESS",
        "MONEY SENT",
        "SENT TO",
        "SENT FROM",
        "SENT FROM YOUR",
        "SENT OF {CUR}",
        "SENT {CUR}",
        "TRANSFERRED TO",
        "TRANSFERRED FROM YOUR",
        "TRANSFERRED FROM YOUR A/C",
        "TRANSFERRED FROM YOUR ACCOUNT",
        "TRANSFERRED {CUR}",
        "TRANSFERRED VIA",
        "TRANSFERRED THROUGH",
        "WE'VE TRANSFERRED {CUR}",
        "WE HAVE TRANSFERRED {CUR}",
        "YOU'VE SPENT {CUR}",
        "YOU HAVE SPENT {CUR}",
        "WITHOUT OTP", 
        "WITHOUT PIN",
        "DEBITED FOR",
        "DEBITED BY",
        "BILL PAYMENT SUCCESSFUL",
        "PAYMENT SUCCESSFUL",
        "STANDING INSTRUCTION EXECUTED",
        "SUCCESSFULLY PAID",
        "PAID RS",
        "PAID INR",
        "DEBITED FOR RS",
        "USED ON SODEXO",
        "ZETA ACCOUNT DEBITED",
        "PLUXEE BALANCE",
        "ನಿಕಾಲೇ ಗಯೇ",
        "निकाले गए"
    )

    val transactionCreditPhrases = setOf(
        "CREDITED TO",
        "{CUR} CREDITED",
        "IS CREDITED WITH",
        "AMT CREDITED",
        "AMOUNT CREDITED",
        "CREDITED {CUR}",
        "MONEY CREDITED",
        "SUCCESSFULLY DEPOSITED",
        "DEPOSITED IN",
        "DEPOSITED TO",
        "AMT DEPOSITED",
        "AMOUNT DEPOSITED IN",
        "RECEIVED IN",
        "RECEIVED ON",
        "RECEIVED TOWARDS",
        "RECEIVED {CUR}",
        "RECIEVED {CUR}", // Typo handling
        "IS RECEIVED",
        "IS RECIEVED", // Typo handling
        "PAYMENT OF {CUR} RECEIVED",
        "PAYMENT OF {CUR} RECIEVED",
        "FUNDS RECEIVED",
        "MONEY RECEIVED",
        "CASHBACK CREDITED",
        "CASHBACK OF {CUR}",
        "REFUND PROCESSED",
        "REFUND CREDITED",
        "REWARD CREDITED",
        "PAYMENT RECEIVED",
        "PAYMENT OF {CUR} IS RECEIVED",
        "PAYMENT OF {CUR} IS RECIEVED",
        "FRESH FUNDS",
        "FUNDS CREDITED",
        "FUNDS TRANSFERRED",
        "TRANSFERRED TO YOUR",
        "TRANSFERRED TO YOUR A/C",
        "TRANSFERRED TO YOUR ACCOUNT",
        "TRANSFER TO YOUR ACCOUNT",
        "TRANSFER FROM",
        "TRANSFERRED FROM",
        "RECEIVED FROM",
        "REFUND OF {CUR}",
        "GOT FRESH FUNDS",
        "ADDED TO YOUR",
        "ADDED TO YOUR ACCOUNT",
        "SALARY CREDITED",
        "TOP-UP SUCCESSFUL",
        "SUCCESSFULLY CREDITED",
        "REVERSAL OF",
        "LOADED IN WALLET",
        "ADDED IN WALLET",
        "जमा किया गया",
        "ईएमआई प्राप्त हुई"
    )

    // --- STAGE 3: INFORMATION (Status / Non-Financial Alerts) ---
    val informationPhrases = setOf(
        "RECHARGE OF {CUR} IS SUCCESSFUL",
        "WILL BE REFUNDED",
        "PAYMENT OF {CUR} HAS FAILED",
        "HAS FAILED",
        "TRANSACTION HAS FAILED",
        "REQUEST FAILED",
        "PAYMENT FAILED",
        "TXN DECLINED",
        "TRANSACTION DECLINED",
        "TXN FAILED",
        "TRANSACTION FAILED",
        "TXN CANCELLED",
        "TRANSACTION CANCELLED",
        "TXN REJECTED",
        "TRANSACTION REJECTED",
        "DECLINED",
        "PAYMENT UNSUCCESSFUL",
        "INSUFFICIENT FUNDS",
        "AVAILABLE BALANCE",
        "CURRENT BALANCE",
        "AVL BAL:",
        "ACCOUNT BALANCE IS",
        "IS NOW BELOW",
        "IS NOW BELOW {CUR}",
        "BALANCE IS LOW",
        "LOW BALANCE",
        "BALANCE AGAINST",
        "REMAINING LIMIT",
        "OTP IS",
        "VERIFICATION CODE IS",
        "CODE TO LOGIN",
        "SECRET CODE",
        "DO NOT SHARE",
        "LOGIN ALERT",
        "DEVICE REGISTERED",
        "PASSWORD FORMAT",
        "KYC RECORD",
        "SERVICE REQUEST",
        "TELL US ABOUT",
        "FEEDBACK ON",
        "PACK IS EXPIRING",
        "VALID TILL",
        "PACK VALID TILL",
        "SMS COST:RS",
        "DATA IS CONSUMED",
        "STATEMENT GENERATED",
        "PIN FOR YOUR",
        "ACTIVATED ON",
        "LIMIT OPTIONS",
        "TDS BY EMPLOYER",
        "YOUR BAL IS",
        "ACCOUNT UPDATED",
        "LOGIN ATTEMPT",
        "PASSWORD RESET",
        "USERNAME FOR",
        "REQUEST FOR",
        "SUCCESSFULLY SET",
        "SIM BINDING CODE",
        "MBACTIVATE",
        "MAB",
        "MONTHLY AVERAGE BALANCE",
        "MONTHLY AVG BAL",

    )

    val otpPhrases = setOf(
        "OTP IS",
        "VERIFICATION CODE IS",
        "CODE TO LOGIN",
        "IS THE OTP FOR",
        "VERIFICATION CODE FOR",
        "DO NOT SHARE OTP",
        "VALID TILL",
        "NEVER SHARE YOUR OTP",
        "TRANSACTION PASSWORD IS",
        "MBACTIVATE",
        "SIM BINDING CODE"
    )

    val otpExcludePhrases = setOf(
        "WITHOUT OTP",
        "WITHOUT PIN",
        "NO OTP REQUIRED"
    )
    
    val strongInformationPhrases = setOf(
        "SUFFICIENT BALANCE",
        "CURRENT BALANCE IS",
        "AVAILABLE BALANCE",
        "AVL BAL:",
        "ACCOUNT BALANCE IS"
    )
}
