package com.example.smartexpensecalendar.sms_engine.direction

object DirectionPatterns {

    val CREDIT_OVERRIDE_SIGNALS = listOf(
        "REFUND",
        "REVERSAL",
        "CASHBACK",
        "INTEREST CREDITED",
        "SALARY"
    )

    val DEBIT_OVERRIDE_SIGNALS = listOf(
        "DEBITED",
        "SPENT",
        "PAID",
        "PURCHASE",
        "WITHDRAWAL",
        "DEDUCTED"
    )

    val PHRASES_CREDIT = listOf(
        "PAYMENT RECEIVED", "RECEIVED TOWARDS", "CREDITED TO", "CREDITED INTO", "CREDITED IN",
        "AMOUNT CREDITED", "AMT CREDITED", "SALARY DEPOSITED", "REFUND CREDITED", "CASHBACK CREDITED",
        "INTEREST CREDITED", "REWARD CREDITED", "FUNDS RECEIVED", "AMOUNT RECEIVED", "RECEIVED FROM",
        "RECEIVED ON", "DEPOSITED INTO", "DEPOSITED TO", "DEPOSITED IN", "DEPOSITED TOWARDS",
        "MONEY RECEIVED", "INWARD REMITTANCE", "RECEIVED VIA UPI", "CREDIT TRANSACTION",
        "CREDITED SUCCESSFULLY", "TOWARDS YOUR CREDIT CARD", "MONEY CREDITED", "SUCCESSFULLY CREDITED",
        "CREDITED WITH", "REVERSAL OF", "LOADED IN WALLET", "ADDED IN WALLET", "GOT FRESH FUNDS"
    )
    val PHRASES_DEBIT = listOf(
        "DEBITED FROM", "DEBITED TOWARDS", "AMOUNT DEBITED", "AMOUNT DEDUCTED", "DEDUCTED FROM",
        "AMT DEDUCTED", "SPENT ON", "SPENT AT", "SPENT FROM", "SPENT USING", "PURCHASE AT",
        "PURCHASE OF", "PURCHASE FOR", "PURCHASE MADE", "PURCHASE USING", "PURCHASE ON",
        "PAID TO", "PAID VIA", "PAID USING", "PAYMENT OF", "CASH WITHDRAWAL", "ATM WITHDRAWAL",
        "WITHDRAWN FROM", "WITHDRAWN AT", "SENT TO", "SENT FROM", "SENT FROM YOUR",
        "MONEY SENT", "MONEY DEBITED", "CHARGED TO", "AUTOPAY SUCCESSFUL", "E-MANDATE SUCCESS",
        "BILL PAYMENT", "MERCHANT PAYMENT", "DEBIT TRANSACTION", "UPI PAYMENT", "WAS DEBITED",
        "SENT FROM YOUR ACCOUNT", "TRANSFERRED FROM YOUR", "SPENT INR", "PAID INR", "SPENT RS", "PAID RS",
        "TXN {CUR}"
    )

    val VERBS_DEBIT = listOf("DEBITED", "SPENT", "PAID", "SENT", "PURCHASED", "USED", "SWIPED", "WITHDRAWN", "TRANSFERRED", "CHARGED", "INITIATED", "DEDUCTED")
    val VERBS_CREDIT = listOf("CREDITED", "RECEIVED", "DEPOSITED", "REFUNDED", "REVERSED", "SALARY", "CASHBACK", "INTEREST", "REWARDED", "RECIEVED", "GOT FRESH FUNDS")

    val DEBIT_ANCHORS = listOf(" AT ", " TO ", " TOWARDS ")
    val CREDIT_ANCHORS = listOf(" FROM ")

    val INSTRUMENT_DEBIT_SIGNALS = listOf("SWIPED", "PURCHASED", "SPENT")
    val INSTRUMENT_CREDIT_SIGNALS = listOf("REFUND", "CASHBACK", "REVERSAL")

    val AMBIGUOUS_SIGNALS = listOf(
        "SUCCESSFUL",
        "COMPLETED",
        "PROCESSED",
        "TRANSACTION"
    )

}